services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    command: --quiet
  parser:
    build: ./parser
    restart: always
    healthcheck:
      test: curl --fail http://parser:3000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 50
  keeper:
    build: ./keeper
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_started
      parser:
        condition: service_healthy
  bot:
    build: ./bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_URL=mongodb://mongo:27017
      - PARSER_URL=http://parser:3000
      - KEEPER_URL=http://keeper:3000
    depends_on:
      parser:
        condition: service_healthy
      keeper:
        condition: service_started
      mongo:
        condition: service_started
  cron:
    build: ./cron
    restart: always
    depends_on:
      keeper:
        condition: service_started

