name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build and Publish" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update application and run new version
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ secrets.REGISTRY }} &&
          cd ${{ secrets.PROJECT_DIR }} &&
          git pull &&
          docker compose -f ./docker-compose.prod.yml pull --parallel --quiet &&
          docker compose -f ./docker-compose.prod.yml up -d --remove-orphans &&
          exit
